### ISSUE TITLE
Modify Error() to generate stack traceback

### ISSUE THREAD

**Issue by kjohnsonecl** [bassklampfe/CodeCoop2Svn#1]
I suggest modifying the Error() routine in utils.lua to generate a stack traceback by making a call to the lua Basic Function error().  A call to Error() is fatal anyhow, and the traceback is likely to be helpful to someone new to this large project.  I can supply modified code.

**Comment by bassklampfe** [comment]
@kjohnsonecl see my comment at #2

**Comment by bassklampfe** [comment]
Just a note: I never had trouble with this. Using [ZeroBraneStudio](https://github.com/pkulchenko/ZeroBraneStudio) i set a breakpoint in Error an could examine everything I needed.
