### ISSUE TITLE
Optionally allow History | Label milestones that are not branches

### ISSUE THREAD

**Issue by kjohnsonecl** [bassklampfe/CodeCoop2Svn#2]
There is a 'Label' option under the Code Co-op History menu that creates a milestone that is not a branch.  There may be other circumstances that create such a milestone as well.  The current code calls Error() when such a label is found.

I suggest an option to allow such labels to be ignored.  The option could be specified in Usage-Example.lua and tested in CodeCoop2Svn.lua.  I can supply such code.

**Comment by jjvbsag** [comment]
@kjohnsonecl 
I did this script only to use it _once_ on the mentioned huge programming project. After that was done, we agreed to release the script to the public, so other people can benefit from this.

If _you_ want to use and change the scripts, feel free to do it the "GitHub" way:

- make a fork under you own GitHub user
- apply your changes there, verify,test and stay happy :smile:
- You can then make a pull request, so I can merge your changes.

:beers:

**Comment by bassklampfe** [comment]
@kjohnsonecl 
I did these scripts to use them _once_ on the mentioned huge code project.  After it was done, we had no use for them any more and decided to release them to the public, so other people can benefit from this project.

If _you_ want to change and use these scripts, please feel free to do it the GitHub way:
- make a fork of the project to your own user
- apply your changes, verify and test and stay happy :smile:
- finally make a pull request, I will then review the patches.

:beers: regards
